name: Build & Upload to TestFlight

on:
  workflow_dispatch:
    branches: [main, hotfix-main]

jobs:
  build-and-upload:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Prepare App Store Connect API key
        run: |
          mkdir -p ./fastlane/private_keys
          echo "${{ secrets.APP_STORE_CONNECT_KEY }}" > ./fastlane/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_KEY_ID }}.p8

      - name: Run Fastlane Beta Lane
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
        run: bundle exec fastlane beta
